version: '3.9'
services:
  django_gunicorn:
    container_name: sentimentbackendlive
    image: sentimentbackend-gunicorn:latest
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env



